namespace:
  name: sandbox

service:
  port: 4111 
  targetPort: 3111 
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests: 
    memory: "64Mi"
    CPU: "250m"
  limits:
    memory: "128Mi"
    CPU: "500m"

containerPort: 3111

livenessProbe:
  HTTP:
    pathHTTP: /healthz
    portHTTP: 3111
readinessProbe: 
  HTTP:
    path: /healthz
    port: 3111
